### ISSUE TITLE
代码写得不错，有没有可能，事务你写得不对

### ISSUE THREAD

**Issue by aveyuan** [Meng-Xin/take-out#4]
![b88d8e5928528dbc71dbf9f6099df5d](https://github.com/Meng-Xin/take-out/assets/10907648/c09325c8-ffbd-46ef-9bcb-36f6a151d989)

代码写得不错，有没有可能，事务你写得不对。开启事务之后，为啥要在函数里面通过recover来捕获然后回滚呢？gorm在数据库查询失败（字段不存在/表不存在等错误）会直接返回错误信息。而非panic（在运行中也不要这么干）。所以，如果有问题会导致事务一直不提交，直到超时。

**Comment by Meng-Xin** [comment]
**问题1：为什么要在函数里通过recover捕获事务错误并进行回滚**
1. 首先这里使用recover捕获事务并进行事务回滚是因为这个是一个设计多表操作，默认情况下gorm的事务力度只针对单个表的增删改查，我把事务提出来是为了满足多表操作的一致性。
2. 为什么使用这种方式做事务操作，这个方式是gorm官方DOC提供的一种标准的事务方式，还有另一种，不过我这里没有展示，具体您可以参考一下gorm事务文档。
**问题2：为什么把事务提到Service层去做**
1. 还是因为事务控制的粒度和范围问题，默认的事务无法满足，所以需要把事务提到Service层去做，这样扩展都更高，能够适应更多的场景。
**问题3：如果某个sql操作超时导致整个链路被卡死问题**
1.这个在当初设计上确实没有想到这个场景，不过好在这个架构的设计模式已经支持我从AOP切面角度去做修复，比如我可以定义gorm中间件来统一控制所有的sql查询超时管理，也可以从代码侵入层面做调整，可以具体到不同的sql不同的超时管理，力度可以细分（这个通过context来做）。
**反馈**
1.您这边有什么建议和设计指导思想可以提出来也可以提MR。

**Comment by Meng-Xin** [comment]
> ![b88d8e5928528dbc71dbf9f6099df5d](https://private-user-images.githubusercontent.com/10907648/326244817-c09325c8-ffbd-46ef-9bcb-36f6a151d989.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5MTU0NjMsIm5iZiI6MTcxNDkxNTE2MywicGF0aCI6Ii8xMDkwNzY0OC8zMjYyNDQ4MTctYzA5MzI1YzgtZmZiZC00NmVmLTliY2ItMzZmNmExNTFkOTg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA1VDEzMTkyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkYWJlMDY1YWMxOTA4NTYyNzdjNTNkZDE1YmRkYTBkOTMxNDY0ZWI4MGJjOGE2NTc2NjUxMDllNDU1ODFlOGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iIg8zZXktveTH8gUtKS9FMC1t7rQLUC-45wVxM6r3zE)
> 
> 代码写得不错，有没有可能，事务你写得不对。开启事务之后，为啥要在函数里面通过recover来捕获然后回滚呢？gorm在数据库查询失败（字段不存在/表不存在等错误）会直接返回错误信息。而非panic（在运行中也不要这么干）。所以，如果有问题会导致事务一直不提交，直到超时。

**问题1：为什么要在函数里通过recover捕获事务错误并进行回滚**
1. 首先这里使用recover捕获事务并进行事务回滚是因为这个是一个设计多表操作，默认情况下gorm的事务力度只针对单个表的增删改查，我把事务提出来是为了满足多表操作的一致性。
2. 为什么使用这种方式做事务操作，这个方式是gorm官方DOC提供的一种标准的事务方式，还有另一种，不过我这里没有展示，具体您可以参考一下gorm事务文档。


**问题2：为什么把事务提到Service层去做**
1. 还是因为事务控制的粒度和范围问题，默认的事务无法满足，所以需要把事务提到Service层去做，这样扩展都更高，能够适应更多的场景。


**问题3：如果某个sql操作超时导致整个链路被卡死问题**
1.这个在当初设计上确实没有想到这个场景，不过好在这个架构的设计模式已经支持我从AOP切面角度去做修复，比如我可以定义gorm中间件来统一控制所有的sql查询超时管理，也可以从代码侵入层面做调整，可以具体到不同的sql不同的超时管理，力度可以细分（这个通过context来做）。


**反馈**
1.您这边有什么建议和设计指导思想可以提出来也可以提MR。

**Comment by aveyuan** [comment]
> > ![b88d8e5928528dbc71dbf9f6099df5d](https://private-user-images.githubusercontent.com/10907648/326244817-c09325c8-ffbd-46ef-9bcb-36f6a151d989.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5MTU0NjMsIm5iZiI6MTcxNDkxNTE2MywicGF0aCI6Ii8xMDkwNzY0OC8zMjYyNDQ4MTctYzA5MzI1YzgtZmZiZC00NmVmLTliY2ItMzZmNmExNTFkOTg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA1VDEzMTkyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkYWJlMDY1YWMxOTA4NTYyNzdjNTNkZDE1YmRkYTBkOTMxNDY0ZWI4MGJjOGE2NTc2NjUxMDllNDU1ODFlOGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iIg8zZXktveTH8gUtKS9FMC1t7rQLUC-45wVxM6r3zE)
> > 代码写得不错，有没有可能，事务你写得不对。开启事务之后，为啥要在函数里面通过recover来捕获然后回滚呢？gorm在数据库查询失败（字段不存在/表不存在等错误）会直接返回错误信息。而非panic（在运行中也不要这么干）。所以，如果有问题会导致事务一直不提交，直到超时。
> 
> **问题1：为什么要在函数里通过recover捕获事务错误并进行回滚**
> 
> 1. 首先这里使用recover捕获事务并进行事务回滚是因为这个是一个设计多表操作，默认情况下gorm的事务力度只针对单个表的增删改查，我把事务提出来是为了满足多表操作的一致性。
> 2. 为什么使用这种方式做事务操作，这个方式是gorm官方DOC提供的一种标准的事务方式，还有另一种，不过我这里没有展示，具体您可以参考一下gorm事务文档。
> 
> **问题2：为什么把事务提到Service层去做**
> 
> 1. 还是因为事务控制的粒度和范围问题，默认的事务无法满足，所以需要把事务提到Service层去做，这样扩展都更高，能够适应更多的场景。
> 
> **问题3：如果某个sql操作超时导致整个链路被卡死问题**
> 
> 1. 这个在当初设计上确实没有想到这个场景，不过好在这个架构的设计模式已经支持我从AOP切面角度去做修复，比如我可以定义gorm中间件来统一控制所有的sql查询超时管理，也可以从代码侵入层面做调整，可以具体到不同的sql不同的超时管理，力度可以细分（这个通过context来做）。
> 
> **反馈**
> 
> 1. 您这边有什么建议和设计指导思想可以提出来也可以提MR。

 **关于问题1**
你提到这是一个跨表事物的问题，手工开启事物是没有问题的，在回滚上问题来了，如果 `insertBatch` 插入失败后会回滚事物吗？你可以测试下

**关于问题2：**
在 `service` 中开启事物没问题。有个额外的问题，回到上个设计问题，这样的实物无法跨越 `service`。比如，a服务会调用b服务（服务间相互调用，实际上很多项目会涉及到，否则就写流水代码），a服务中的事物回滚了，b服务无法回滚，该怎么解决呢？

**关于问题3**
实质上不是 `aop` 问题，还是问题1的问题。因为程序本身没有 `recover` 然后又返回了err，事物既然没有回滚又没有提交操作，导致在数据库层面上一直锁事物。直到数据库的锁超时后解锁。（卡住的不是程序，而是数据库的事物锁，你可以测试下）

**结束**
以上只是个人上的一些建议看法。希望对你的设计有所帮助。

**Comment by Schofi** [comment]
good question

**Comment by luminescenceJ** [comment]
defer 语句会在 函数返回之前 执行，但它会在 return 语句执行后，即函数返回值确定后才执行。
这里就需要手动确定返回值的类型了，如果存在err也会触发回滚
defer func() {
		if r := recover(); r != nil {
			// 发生 panic 时回滚事务
			transaction.Rollback()
		} else if err != nil {
			// 发生错误时回滚事务
			transaction.Rollback()
		} else {
			// 如果没有错误，提交事务
			transaction.Commit()
		}
	}()
